//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSettings
    {
        public int ID { get; set; }
        public string SmptServer { get; set; }
        public string MailTo { get; set; }
        public string MailAddress { get; set; }
        public string MailPassword { get; set; }
    }
}
